### ISSUE TITLE
Consider using babel-preset-latest / babel-preset-env

### ISSUE THREAD

**Issue by glebec** [FullstackAcademy/bones#81]
`babel-preset-latest` automatically includes multiple presets according to whatever is current. For example as of this writing it includes:

* `babel-preset-es2015`
* `babel-preset-es2016`
* `babel-preset-es2017`

This might be useful for keeping Bones able to handle relatively up-to-date JS.

Oddly, `async/await` appears to been a special plugin to transpile. More research is needed to determine the optimal setup.

**Comment by glebec** [comment]
https://github.com/babel/babel-preset-env is also a strong contender. With this, we can target the current Node version, current browser versions, etc. No more nitty-gritty config, instead we declaratively stay on top of the latest features.

**Comment by aardito2** [comment]
`babel-preset-latest` is already deprecated in favor of `babel-preset-env`, see https://github.com/babel/babel/issues/5637

**Comment by hzoo** [comment]
Yeah preset-env without options is the same as preset-latest, so there's no reason to not use it (FYI i'm it's the creator and maintain Babel). Yep point is that no one would need to update the yearly presets (and we won't have to create them anymore)
